export const START_SEARCH_REPOS = 'START_SEARCH_REPOS'
export const SEARCH_REPOS_SUCCESS = 'SEARCH_REPOS_SUCCESS'
export const SEARCH_REPOS_FAIL = 'SEARCH_REPOS_FAIL'

export const FETCH_ISSUE_START = 'FETCH_ISSUE_START'
export const FETCH_ISSUE_SUCCESS = 'FETCH_ISSUE_SUCCESS'
export const FETCH_ISSUE_FAIL = 'FETCH_ISSUE_FAIL'